jenkins:
  systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."
  securityRealm:
    local:
      users:
       - id: chocolateen
         password: ${USER_CHOCOLATEEN_PASSWORD}
       - id: vaugie_g
         password: ${USER_VAUGIE_G_PASSWORD}
       - id: i_dont_know
         password: ${USER_I_DONT_KNOW_PASSWORD}
       - id: nasso
         password: ${USER_NASSO_PASSWORD}
  authorizationStrategy:
    roleBased:
      roles:
        global:
          - name: "admin"
            description: "Marvin master"
            permissions:
              - "Overall/Administer"
            assignments:
              - "chocolateen"
          - name: "ape"
            description: "Pedagogical team member"
            permissions:
              - "Job/Build"
              - "Overall/Read"
            assignments:
              - "i_dont_know"
          # - name: "gorilla"
          #   description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
          #   permissions:
          #     - "Overall/Administer"
          #   assignments:
          #     - "vaugie_g"
          - name: "assist"
            description: "Assistant"
            permissions:
              - "Overall/Read"
              - "Job/Read"
            assignments:
              - "nasso"

jobs:
  - file: job_dsl.groovy
